### ISSUE TITLE
Annotations, highlights and handwritings is not being saved

### ISSUE THREAD

**Issue by brunoinds** [Adventech/sabbath-school-ios#176]
The highlighting and notes in the lessons is no longer being saved after closing the application. The original PDF handwriting is not being saved as well.

**Comment by VitalikL** [comment]
@brunoinds Just to confirm, can you provide a screen recording of the issue - I can not reproduce it on my end. Also, you are connected to the internet when it happens, right?

**Comment by brunoinds** [comment]
Hi @VitalikL! Yes, the steps to reproduce the error is:

1. Open the application with internet connection and choose a lesson
2. Disable internet connection
3. Make a highlight on the text (does not matter if is in the original PDF or in the markdown lesson itself)
4. Close de application
5. Connect to the internet again
6. Open the lesson (the highlights are not longer there)

I know the highlights/annotations are probably saved on the server-side. But sometimes, not all iPads has cellular data available in everywere (specially in crowded churches or other scenarios), so a localStorage or some kind of client-side cache could be implemented to avoid this unexpected behavior in the point of view of the user. So, when the connection returns, the data could be pushed and syncronized with the server.

**Comment by mrlad** [comment]
I'm seeing the same/similar problem on my iPad and I'm connected to the internet 100% of the time.  What I'm seeing is that my highlights and comments from Saturday and Sunday tend to be preserved but all the highlights for the rest of the week aren't saved/preserved.

I also have an android phone and the changes aren't synced.

I just noticed the problem two weeks ago and it happened again this week.  I will try to create a replication scenario.

**Comment by mrlad** [comment]
My annotations for today disappeared after I switched away to another app (X in this case).  Had a WiFi connection when this occurred.  So I think we can rule out internet connectivity as the cause.

**Comment by mrlad** [comment]
Still haven't nailed down a scenario.  Tonight, I added comments under two questions and added a highlight, switched away and killed the app.  The comments and highlights were gone.

Then tried the same scenario with just the comments, and they were preserved.

Tried just a highlight with the same scenario, and it was preserved.

I wonder if the app gets killed prior to syncing, the changes are lost?  Is there a way to force a sync?

**Comment by brunoinds** [comment]
@mrlad Interesting! I think we should use the optimistic UI approach. Where all annotations (comments,highlights...) are first saved locally on the device memory, and, asynchronously pushed to the server. So, if the app is killed, the device will first get the annotations that are on the device memory first and retry to upload them. When each annotation is pushed, they are removed from the device memory.

**Comment by VitalikL** [comment]
@brunoinds @mrlad The next version is going to support the locally saved annotations, comments & etc, with the synchronization upon the next time internet connection becomes available.

**Comment by mrlad** [comment]
Do you have a beta testing process (i.e. TestFlight) to verify fixes before they're officially pushed to the App Store?

**Comment by VitalikL** [comment]
@mrlad Yes we use TestFlight for testing. If you are interested to be part of it, let me know by email your appleid / email so i can add you

**Comment by mrlad** [comment]
Yes I'm interested in beta testing with TestFlight.  Where can I find your email address so I can send the requested info?

**Comment by VitalikL** [comment]
@mrlad @brunoinds We made some changes on the backend, please confirm if you are still experiencing this issue

**Comment by brunoinds** [comment]
@VitalikL Thanks for the changes made! I appreciated that 😀! But, I still continue experiencing the issue. I've followed the same steps that I've mentioned here:


> Hi [@VitalikL](https://github.com/VitalikL)! Yes, the steps to reproduce the error is:
> 
> 1. Open the application with internet connection and choose a lesson
> 2. Disable internet connection
> 3. Make a highlight on the text (does not matter if is in the original PDF or in the markdown lesson itself)
> 4. Close de application
> 5. Connect to the internet again
> 6. Open the lesson (the highlights are not longer there)
> 
> I know the highlights/annotations are probably saved on the server-side. But sometimes, not all iPads has cellular data available in everywere (specially in crowded churches or other scenarios), so a localStorage or some kind of client-side cache could be implemented to avoid this unexpected behavior in the point of view of the user. So, when the connection returns, the data could be pushed and syncronized with the server.

I don't know really well how the annotation saving is being implemented. But, it looks like it's more about a front-end issue rather than a back-end problem... 🤔

**Comment by VitalikL** [comment]
@brunoinds Ahh, now I understand, I thought there issue with the active network connection and there was one issue on backend, which we fixed. With regards to offline annotation and notes sync, this will be coming in the upcoming release.

Thank you!

**Comment by mrlad** [comment]
I've not had a problem the last couple of days.  When did the change roll out?

**Comment by mrlad** [comment]
@VitalikL , reminder, I still need an email address so I can sign up for Testflight.  You don't have one in your github profile.

**Comment by mrlad** [comment]
BTW, sync between Andriod and iOS is working again which is nice.

**Comment by mrlad** [comment]
Hi @VitalikL , reminder, I would like to sign up for test flight but don't have an email address to send the request to.  Please explain how I can obtain the sign up email address from you.

**Comment by mrlad** [comment]
Noticed this morning that my annotations and highlights from Tue->Fri of last week were all lost.

**Comment by iRoachie** [comment]
Chiming in here folks. Also experienced the same exact thing as @mrlad. I was studying with an active connection though.

Got up to teach last sabbath and realized all my notes were gone 🙈

Would be happy to test for you guys. My testflight email is roach_kyle@me.com

**Comment by mrlad** [comment]
@iRoachie , LOL, same issue with me.  Was doing final prep for teaching SS class and discovered almost all of my notes were gone!

**Comment by mrlad** [comment]
I lost my annotations and highlights from Mon->Fri of last week on Sabbath morning.  However, I narrowed down the problem a bit.  On Friday evening, I navigated to week 11 to see what the memory text was and then came back the next day to review the lesson.  The annotations were present prior to navigating to week 11 and were gone after.

Its not quite as simple as switching weeks cause I've tried that subsequently and having lost my new annotations.

**Comment by VitalikL** [comment]
@mrlad are you by any chance using multiple devices (including Android) or is it single iOS device?

**Comment by VitalikL** [comment]
> Chiming in here folks. Also experienced the same exact thing as [@mrlad](https://github.com/mrlad). I was studying with an active connection though.
> 
> Got up to teach last sabbath and realized all my notes were gone 🙈
> 
> Would be happy to test for you guys. My testflight email is [roach_kyle@me.com](mailto:roach_kyle@me.com)

Just to double check, we had an issue with highlights on Android and fixed it, just wanted to make sure you were using iOS device

**Comment by mrlad** [comment]
Primarily iOS (iPad) but occasional Android usage (but haven't used Android in a couple of weeks).

Problem happened again Sabbath morning but this time I was carefully monitoring the state of the annotations. Was on Friday, double checked that the annotations were in tact. Visited the Sabbath lesson in the next week, then immediately came back.  Annotations Mon->Fri were lost again.

**Comment by iRoachie** [comment]
> > Chiming in here folks. Also experienced the same exact thing as [@mrlad](https://github.com/mrlad). I was studying with an active connection though.
> > Got up to teach last sabbath and realized all my notes were gone 🙈
> > Would be happy to test for you guys. My testflight email is [roach_kyle@me.com](mailto:roach_kyle@me.com)
> 
> Just to double check, we had an issue with highlights on Android and fixed it, just wanted to make sure you were using iOS device

Yes i’m using iOS. Have an iPad and iPhone.

**Comment by mrlad** [comment]
@iRoachie , when you lost your annotations, by any chance, were you switching weeks?

**Comment by iRoachie** [comment]
@mrlad that’s very possible. I often check back previous week’s notes

**Comment by VitalikL** [comment]
@mrlad @iRoachie are you guys referring to the PDF annotations or the main text comments and highlights?

I was still not able to reproduce the comments / highlights issue with the text version, but the PDF does have outstanding issue where annotations only work for the first tab. We already fixed PDF annotations bug and will release it soon

**Comment by iRoachie** [comment]
> [@mrlad](https://github.com/mrlad) [@iRoachie](https://github.com/iRoachie) are you guys referring to the PDF annotations or the main text comments and highlights?
> 
> I was still not able to reproduce the comments / highlights issue with the text version, but the PDF does have outstanding issue where annotations only work for the first tab. We already fixed PDF annotations bug and will release it soon

Referring to the regular version, not pdf. I’ll monitor it and report back if it happens again. My mother has even complained about this to me 🙈

**Comment by mrlad** [comment]
I was also referring to the main text, not pdf.

I have a mix of highlights and answer the question in the lesson.  Both the answers and the highlights disappear.

**Comment by mrlad** [comment]
Discovered some new info.  Prior to advancing to the next week, I checked on Android to see how much info had been pushed to the cloud and synced.  Turns out Sun->Mon comments/highlights were synced but Tue-Thu didn't sync.  Relatively sure that I will lose the Tue-Thu data like previous weeks when I advance to the next week and come back.

It would appear as if the Tue-Thu is failing to sync and not stored anywhere.

**Comment by mrlad** [comment]
Narrowing the problem down a bit more.  I verified the Tue-Thu highlights and annotations were still visible, then killed the app.  When the app restarted, the annotations were gone. 

So it would appear as if visiting the next week and coming back was a red herring and not the root cause.  The problem is visible if you kill and/or restart the app or try to sync with android when in this state.  The root cause is for some reason, Tue-Fri changes on my account never sync.  Sat->Mon seem to sync.

**Comment by mrlad** [comment]
I will try to verify permanent storage of the annotations Mon/Tue as that seems to be the boundary condition where data is lost (at least for me).

**Comment by mrlad** [comment]
Made the Monday annotations in iOS.  They still haven't showed up on Android.  I suspect they will be lost.  Sat/Sun annotation are visible on Android.

**Comment by mrlad** [comment]
Monday's annotation hasn't synced after 30+ hours and Tuesday hasn't synced.  At this point, doesn't appear like they will sync.

**Comment by VitalikL** [comment]
@mrlad What android app version you are using?

**Comment by mrlad** [comment]
Android: I'm on 5.5.0 (updated March 18)
iOS: 4.0.0 (last update a couple months ago)

I still don't have the info to join testflight so my iOS updates are coming from the AppStore.

**Comment by mrlad** [comment]
Wednesday's changes on iOS synced after the iOS app was restarted.

**Comment by mrlad** [comment]
So far this week. Saturday has synced, Sun/Mon haven't synced.  I killed the iOS app and the Sun/Mon annotations are gone (as expected).  This seems to confirm my previous experiences that failure to see the data on Android means that the annotations will eventually be lost inside iOS even thought he annotations show on the screen prior to the app being killed and restarted.

**Comment by mrlad** [comment]
I'm working on a theory that multi-line annotated text comments sync, whereas single line comments don't sync.

Monday has multiple questions/verses to comment on.  Multi-line comments synced immediately.  Single line comments partially synced (some synced, others didn't).

Is it possible that Multi-line comments are properly detected as needing permanent storage whereas single line comments aren't (bug?)  Most of my comments tend to be single line without hitting the return key for extra lines.

**Comment by VitalikL** [comment]
Thanks for helping navigate this issue @mrlad . It is highly unlikely that it has anything to do with single-line vs multi-line. Nevertheless, we will also check that. Most probably, in certain scenarios the call to sync the notes is either not called or is not fully finished. Lastly, it could be some issue with the type mismatch, which I am investigating right now

**Comment by mrlad** [comment]
You were correct @VitalikL . I had some multi-line comments fail to sync this week.

**Comment by mrlad** [comment]
For the last 4-5 weeks, I've been able to avoid losing data by not leaving the current lesson until the week was over.  This morning, the app had exited the current lesson on its own (not sure why) and when I launched it this morning, it was at the main screen where you pick the lesson to study. 

Sure enough, when I opened the current lesson, my changes for this week were lost.   I'm guessing the app either crashed or iPadOS restarted it (not sure which happened).

**Comment by VitalikL** [comment]
@brunoinds @mrlad Thanks. We have fixed a critical issue on the backend yesterday that was related to race condition and could have potentially contributed to the highlights / notes / annotations being lost. In order to verify if what you are experiencing was related to that can you please log out and log back in on your devices and see if the syncing is fixed. Thanks!

PS: We have also been implementing the locally saved version and it will be released soon.

**Comment by mrlad** [comment]
Just saw your message tonight. Logged out.  When I logged back in, I lost my annotations from Mon->Wed but still had Sunday.  After logging back in, gradually reconstructing my highlights and notes for the week.  After each day, I've exited the current week's lesson.  So far, after logging back in, I've not lost new highlights. 

Too early to determine if your race condition fix solved my use case, but initial results are positive.

**Comment by VitalikL** [comment]
@mrlad @brunoinds let me know if you want to get unto TestFlight, the beta version now have offline comments / highlights implemented. You can either give me your email for TestFlight here or email me vitaliy [@] adventech.io

**Comment by mrlad** [comment]
The race condition fix didn't solve my issue, I lost Tuesday's notes and highlights be exiting the current lesson and going back to the home page.  Sun/Mon are ok.

**Comment by mrlad** [comment]
@VitalikL ,

Downloaded the beta.  My highlights/notes from this morning (Wednesday) were lost.  Will monitor daily by exiting and re-entering the current day.

**Comment by VitalikL** [comment]
@mrlad current beta implements offline notes, highlights, underlines sync. The sync will happen next time you open same lesson with internet connection. Hopefully this will resolve the rogue data loss. 

PS: we will work on uploading unsynced data anytime when the connection is restored, but for now it has to be opened the same lesson

**Comment by mrlad** [comment]
@VitalikL , I've been trying very day for 3 weeks and have not been able to replicate this bug with the beta.  Seems fixed to me.

**Comment by mrlad** [comment]
When the official release comes out, I'll test again
